[package]
name = "rsmq_async"
version = "5.0.0"
authors = ["David Bonet <webbonet@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Async RSMQ port to rust. RSMQ is a simple redis queue system that works in any redis v2.4+. It contains the same methods as the original one in https://github.com/smrchy/rsmq"
homepage = "https://crates.io/crates/rsmq_async"
repository = "https://github.com/Couragium/rsmq-async-rs"
documentation = "https://docs.rs/rsmq_async/"
readme = "README.md"

[dependencies]
lazy_static = "1.4"
rand = "0.8"
radix_fmt = "1.0"
bb8 = "0.7"
thiserror = "1.0.20"
redis = {version = "0.18.0", features = ["tokio-comp", "async-std-comp"]}
async-trait = "0.1.40"

[dev-dependencies]
net2 = "0.2.33"

[dev-dependencies.tokio]
version = "0.2.11"
