[package]
name = "rsmq-rs"
version = "1.0.2"
authors = ["David Bonet <webbonet@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Async RSMQ port to rust. RSMQ is a simple redis queue system that works in any redis v2.4+. It contains the same methods as the original one iin https://github.com/smrchy/rsmq"
homepage = "https://github.com/Couragium/rsmq-rs"
repository = "https://github.com/Couragium/rsmq-rs"
documentation = "https://docs.rs/rsmq-rs/"
readme = "README.md"

[dependencies]
redis = "0.15.1"
lazy_static = "1.4.0"
rand = "0.7.3"
radix_fmt = "1.0.0"
