name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - name: Install Redis server
      with:
        command: apt
        args: install redis-server

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Cargo Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Cargo Fmt Check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Cargo Test
      uses: actions-rs/cargo@v1
      with:
        command: test
